### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [narutoo9x/BlogApp-PreWork#2]
Hi Thanh, thanks for the great work! Below are some comments:

##  Great Things
You've used gems such as impressionist, searchkick, and acts_as_taggable for the extra features. It's nice to see that you're trying out acts_as_votable too.
The UI looks good.
Good job at defining the root in config/routes.rb.

## Suggestions
You could add some validations in the articles or comments models.
Please add your picture and profile in a post.

Feel free to update your submission because we'll check it again soon.

**Comment by narutoo9x** [comment]
After @harley had said I use too much gem, I should do it by myself and suggested I build tagging from scratch. I removed acts_as_taggable, and I did it.
I will update my submission soon.

**Comment by narutoo9x** [comment]
I added validations and a posted a picture to the blog.
